app/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class Humanbeing(UserMixin, db.Model):
    """Create an Human being table"""
    __tablename__ = 'humanbeings'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), index=True, unique=True)
    callname = db.Column(db.String(255), index=True, unique=True)
    first_name = db.Column(db.String(255), index=True)
    last_name = db.Column(db.String(255), index=True)
    password_hash = db.Column(db.String(128))
    address_id = db.Column(db.Integer, db.ForeignKey('addresses.id'))
    is_admin =  db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """Password acces prevention."""
        raise AttributeError('Password is not readable, for safy reason.')

    @password.setter
    def password(self, password):
        """Make the password hashed"""
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """Check if hashed password is correct"""
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<Human being: {}>'.format(self.callname)

@login_manager.user_loader
def load_user(user_id):
    return Humanbeing.query.get(int(user_id))


class Address(db.Model):
    """Table for adresses"""
    __tablename__ = 'addresses'

    id = db.Column(db.Integer, primary_key=True)
    road = db.Column(db.String(255), unique=True)
    postalcode = db.Column(db.Integer)
    contry = db.Column(db.String(255))
    Humanbeing = db.relationship('Humanbeing', backref='adress', lazy='dynamic')

    def __repr__(self):
        return '<Adress: {}>'.format(self.road)

    

app/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy

from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate

from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__, instance_relative_config=True, static_url_path='/static')
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('../config.py')
    db.init_app(app)
    bootstrap = Bootstrap(app)
    migrate = Migrate(app, db)

    from app import models

    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    @app.route('/404')
    def NoFound404():
        return render_template("404.html")

    @app.route('/')
    def index():
        return render_template("index.html")

    @app.route('/about')
    def about():
        return render_template("about.html")

    login_manager.init_app(app)
    login_manager.login_message = "Login, before accessing this page."
    login_manager.login_view = "auth.login"

    return app

app/home/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import render_template
from flask_login import login_required

from . import home


@home.route('/')
def homepage():
    """Render """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """ """
    return render_template('home/dashboard.html', title="Dashboard")
    

app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import render_template

app/templates/about.html
{% extends 'base.html' %}
{% block title %}About FlaskMVC{% endblock %}
{% block body %}
<div class="jumbotron">
    <h1>About</h1>
    <p>More about the FlaskMVC.</p>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<head>
    {{ bootstrap.load_css() }}
</head>
{% block title %}
    {% if title %}{{ title }} - FlaskMVC{% else %}Welcome to this FlaskMVC{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-dark bg-dark navbar-fixed-top topnav">
        <div class="container-fluid topnav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#MyNavbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="{{ url_for('index') }}">Flask test</a>
            </div>
            <div class="collapse navbar-collapse" id="MyNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                    <li><a href="#">Register</a></li>
                    <li><a href="#">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

<div class="wrapper">
    {% block body %}
    {% endblock %}
    <div class="push"></div>
</div>

{% block content %}
    {{ bootstrap.load_js() }}
{% endblock %}

app/templates/home/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Project Home Team</h1>
                    <h3>The best place in the world!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %}FlaskMVC main site{% endblock %}
{% block body %}
<div class="jumbotron">
    <h1>Wim Hof Method == Awesome</h1>
    <p>and so is <i>Flask</i>(<b>Python</b>) btw ;-)</p>
</div>
{% endblock %}